
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "\x0c\x06\xfao@\\\x8f\xeb\xea\xafo\x02'N\xe5\x1e"
    
_lr_action_items = {'RIGHTBRACKET':([21,22,23,35,],[28,-18,-19,-17,]),'MULTIEXPR':([8,11,12,13,14,15,16,17,19,20,27,28,33,37,],[16,16,-11,-9,-13,-12,-14,-10,16,-15,16,-16,-21,-20,]),'ASSIGNS':([3,4,7,28,],[8,-15,11,-16,]),'ANYEXPR':([8,11,12,13,14,15,16,17,19,20,27,28,33,37,],[14,14,-11,-9,-13,-12,-14,-10,14,-15,14,-16,-21,-20,]),'OUTPUTS':([12,13,14,15,16,17,18,19,20,24,26,28,33,37,],[-11,-9,-13,-12,-14,-10,25,-8,-15,30,-7,-16,-21,-20,]),'LEFTPAREN':([20,],[27,]),'LITERAL':([8,11,12,13,14,15,16,17,19,20,27,28,33,37,],[15,15,-11,-9,-13,-12,-14,-10,15,-15,15,-16,-21,-20,]),'RIGHTPAREN':([12,13,14,15,16,17,19,20,26,27,28,33,34,37,],[-11,-9,-13,-12,-14,-10,-8,-15,-7,33,-16,-21,37,-20,]),'LEFTBRACKET':([3,4,8,11,12,13,14,15,16,17,19,20,27,28,33,37,],[9,-15,9,9,-11,-9,-13,-12,-14,-10,9,-15,9,-16,-21,-20,]),'COMMA':([22,23,],[29,-19,]),'STRING':([25,30,],[31,31,]),'ID':([0,2,5,8,9,11,12,13,14,15,16,17,19,20,27,28,29,31,32,33,36,37,],[4,4,4,20,23,20,-11,-9,-13,-12,-14,-10,20,-15,20,-16,23,-22,-6,-21,-5,-20,]),'$end':([1,2,5,6,10,31,32,36,],[0,-2,-4,-1,-3,-22,-6,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'category':([3,8,11,19,27,],[7,12,12,12,12,]),'mathml':([8,11,19,27,],[13,13,13,13,]),'database':([0,],[1,]),'pattern':([0,2,5,],[2,5,5,]),'categValues':([9,29,],[21,35,]),'categValue':([9,29,],[22,22,]),'patterns':([2,5,],[6,10,]),'variable':([0,2,5,8,11,19,27,],[3,3,3,17,17,17,17,]),'output':([25,30,],[32,36,]),'expressions':([8,11,19,27,],[18,24,26,34,]),'expression':([8,11,19,27,],[19,19,19,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> database","S'",1,None,None,None),
  ('database -> pattern patterns','database',2,'p_program','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',72),
  ('database -> pattern','database',1,'p_program','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',73),
  ('patterns -> pattern patterns','patterns',2,'p_patterns','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',83),
  ('patterns -> pattern','patterns',1,'p_patterns','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',84),
  ('pattern -> variable category ASSIGNS expressions OUTPUTS output','pattern',6,'p_pattern','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',94),
  ('pattern -> variable ASSIGNS expressions OUTPUTS output','pattern',5,'p_pattern','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',95),
  ('expressions -> expression expressions','expressions',2,'p_expressions','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',105),
  ('expressions -> expression','expressions',1,'p_expressions','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',106),
  ('expression -> mathml','expression',1,'p_expression','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',117),
  ('expression -> variable','expression',1,'p_expression','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',118),
  ('expression -> category','expression',1,'p_expression','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',119),
  ('expression -> LITERAL','expression',1,'p_expression','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',120),
  ('expression -> ANYEXPR','expression',1,'p_expression','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',121),
  ('expression -> MULTIEXPR','expression',1,'p_expression','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',122),
  ('variable -> ID','variable',1,'p_variable','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',135),
  ('category -> LEFTBRACKET categValues RIGHTBRACKET','category',3,'p_category','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',142),
  ('categValues -> categValue COMMA categValues','categValues',3,'p_categValues','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',149),
  ('categValues -> categValue','categValues',1,'p_categValues','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',150),
  ('categValue -> ID','categValue',1,'p_categValue','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',164),
  ('mathml -> ID LEFTPAREN expressions RIGHTPAREN','mathml',4,'p_mathml','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',171),
  ('mathml -> ID LEFTPAREN RIGHTPAREN','mathml',3,'p_mathml','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',172),
  ('output -> STRING','output',1,'p_output','/home/spencer/workspace/NiftyProseArticulator/src/mathml/database.py',182),
]
