# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GraffeS.PC93667W7\git\central-access-reader\car\forms/color_settings.ui'
#
# Created: Fri May 30 14:46:26 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ColorSettings(object):
    def setupUi(self, ColorSettings):
        ColorSettings.setObjectName(_fromUtf8("ColorSettings"))
        ColorSettings.resize(275, 565)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/classic/icons/color_settings_classic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ColorSettings.setWindowIcon(icon)
        self.verticalLayout_9 = QtGui.QVBoxLayout(ColorSettings)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(ColorSettings)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 256, 666))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setSpacing(40)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet(_fromUtf8("font-size: 16pt;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.enableHTextCheckBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.enableHTextCheckBox.setObjectName(_fromUtf8("enableHTextCheckBox"))
        self.verticalLayout.addWidget(self.enableHTextCheckBox)
        self.enableHLineCheckBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.enableHLineCheckBox.setObjectName(_fromUtf8("enableHLineCheckBox"))
        self.verticalLayout.addWidget(self.enableHLineCheckBox)
        self.followInsideParagraphCheckBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.followInsideParagraphCheckBox.setObjectName(_fromUtf8("followInsideParagraphCheckBox"))
        self.verticalLayout.addWidget(self.followInsideParagraphCheckBox)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setStyleSheet(_fromUtf8("font-size: 16pt;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.contentBackgroundButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.contentBackgroundButton.setObjectName(_fromUtf8("contentBackgroundButton"))
        self.horizontalLayout_3.addWidget(self.contentBackgroundButton)
        self.contentTextButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.contentTextButton.setObjectName(_fromUtf8("contentTextButton"))
        self.horizontalLayout_3.addWidget(self.contentTextButton)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet(_fromUtf8("font-size: 16pt;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.highlighterBackgroundButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterBackgroundButton.setObjectName(_fromUtf8("highlighterBackgroundButton"))
        self.horizontalLayout_4.addWidget(self.highlighterBackgroundButton)
        self.highlighterTextButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterTextButton.setObjectName(_fromUtf8("highlighterTextButton"))
        self.horizontalLayout_4.addWidget(self.highlighterTextButton)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet(_fromUtf8("font-size: 16pt;"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.highlighterLineBackgroundButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterLineBackgroundButton.setObjectName(_fromUtf8("highlighterLineBackgroundButton"))
        self.horizontalLayout_5.addWidget(self.highlighterLineBackgroundButton)
        self.highlighterLineTextButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterLineTextButton.setObjectName(_fromUtf8("highlighterLineTextButton"))
        self.horizontalLayout_5.addWidget(self.highlighterLineTextButton)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet(_fromUtf8("font-size: 16pt;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.fontComboBox = QtGui.QFontComboBox(self.scrollAreaWidgetContents)
        self.fontComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.verticalLayout_5.addWidget(self.fontComboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet(_fromUtf8("font-size: 16pt;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.themeComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.themeComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.themeComboBox.setObjectName(_fromUtf8("themeComboBox"))
        self.verticalLayout_6.addWidget(self.themeComboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.restoreButton = QtGui.QPushButton(ColorSettings)
        self.restoreButton.setObjectName(_fromUtf8("restoreButton"))
        self.verticalLayout_7.addWidget(self.restoreButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)

        self.retranslateUi(ColorSettings)
        QtCore.QMetaObject.connectSlotsByName(ColorSettings)
        ColorSettings.setTabOrder(self.contentBackgroundButton, self.contentTextButton)
        ColorSettings.setTabOrder(self.contentTextButton, self.highlighterBackgroundButton)
        ColorSettings.setTabOrder(self.highlighterBackgroundButton, self.highlighterTextButton)
        ColorSettings.setTabOrder(self.highlighterTextButton, self.highlighterLineBackgroundButton)
        ColorSettings.setTabOrder(self.highlighterLineBackgroundButton, self.highlighterLineTextButton)

    def retranslateUi(self, ColorSettings):
        ColorSettings.setWindowTitle(_translate("ColorSettings", "Highlighting, Colors, and Fonts", None))
        self.label_8.setText(_translate("ColorSettings", "Highlighting", None))
        self.enableHTextCheckBox.setText(_translate("ColorSettings", "Word", None))
        self.enableHLineCheckBox.setText(_translate("ColorSettings", "Sentence", None))
        self.followInsideParagraphCheckBox.setText(_translate("ColorSettings", "Follow Inside Paragraph", None))
        self.label_6.setText(_translate("ColorSettings", "Content", None))
        self.contentBackgroundButton.setText(_translate("ColorSettings", "Background", None))
        self.contentTextButton.setText(_translate("ColorSettings", "Text", None))
        self.label_4.setText(_translate("ColorSettings", "Highlighter Word", None))
        self.highlighterBackgroundButton.setText(_translate("ColorSettings", "Background", None))
        self.highlighterTextButton.setText(_translate("ColorSettings", "Text", None))
        self.label_5.setText(_translate("ColorSettings", "Highlighter Sentence", None))
        self.highlighterLineBackgroundButton.setText(_translate("ColorSettings", "Background", None))
        self.highlighterLineTextButton.setText(_translate("ColorSettings", "Text", None))
        self.label_9.setText(_translate("ColorSettings", "Font", None))
        self.label_2.setText(_translate("ColorSettings", "Theme", None))
        self.restoreButton.setToolTip(_translate("ColorSettings", "Restores settings to their default values", None))
        self.restoreButton.setText(_translate("ColorSettings", "Restore to Default Settings", None))

import resource_rc
