# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GraffeS.PC93667W7\git\central-access-reader\car/forms/color_settings.ui'
#
# Created: Wed Jun 11 15:37:24 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ColorSettings(object):
    def setupUi(self, ColorSettings):
        ColorSettings.setObjectName("ColorSettings")
        ColorSettings.resize(275, 565)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/classic/icons/color_settings_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ColorSettings.setWindowIcon(icon)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(ColorSettings)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(ColorSettings)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 256, 666))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setSpacing(40)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet("font-size: 16pt;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.enableHTextCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.enableHTextCheckBox.setObjectName("enableHTextCheckBox")
        self.verticalLayout.addWidget(self.enableHTextCheckBox)
        self.enableHLineCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.enableHLineCheckBox.setObjectName("enableHLineCheckBox")
        self.verticalLayout.addWidget(self.enableHLineCheckBox)
        self.followInsideParagraphCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.followInsideParagraphCheckBox.setObjectName("followInsideParagraphCheckBox")
        self.verticalLayout.addWidget(self.followInsideParagraphCheckBox)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setStyleSheet("font-size: 16pt;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contentBackgroundButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.contentBackgroundButton.setObjectName("contentBackgroundButton")
        self.horizontalLayout_3.addWidget(self.contentBackgroundButton)
        self.contentTextButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.contentTextButton.setObjectName("contentTextButton")
        self.horizontalLayout_3.addWidget(self.contentTextButton)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("font-size: 16pt;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.highlighterBackgroundButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterBackgroundButton.setObjectName("highlighterBackgroundButton")
        self.horizontalLayout_4.addWidget(self.highlighterBackgroundButton)
        self.highlighterTextButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterTextButton.setObjectName("highlighterTextButton")
        self.horizontalLayout_4.addWidget(self.highlighterTextButton)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("font-size: 16pt;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.highlighterLineBackgroundButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterLineBackgroundButton.setObjectName("highlighterLineBackgroundButton")
        self.horizontalLayout_5.addWidget(self.highlighterLineBackgroundButton)
        self.highlighterLineTextButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.highlighterLineTextButton.setObjectName("highlighterLineTextButton")
        self.horizontalLayout_5.addWidget(self.highlighterLineTextButton)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet("font-size: 16pt;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.fontComboBox = QtWidgets.QFontComboBox(self.scrollAreaWidgetContents)
        self.fontComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.fontComboBox.setObjectName("fontComboBox")
        self.verticalLayout_5.addWidget(self.fontComboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet("font-size: 16pt;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.themeComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.themeComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.themeComboBox.setObjectName("themeComboBox")
        self.verticalLayout_6.addWidget(self.themeComboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.restoreButton = QtWidgets.QPushButton(ColorSettings)
        self.restoreButton.setObjectName("restoreButton")
        self.verticalLayout_7.addWidget(self.restoreButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)

        self.retranslateUi(ColorSettings)
        QtCore.QMetaObject.connectSlotsByName(ColorSettings)
        ColorSettings.setTabOrder(self.contentBackgroundButton, self.contentTextButton)
        ColorSettings.setTabOrder(self.contentTextButton, self.highlighterBackgroundButton)
        ColorSettings.setTabOrder(self.highlighterBackgroundButton, self.highlighterTextButton)
        ColorSettings.setTabOrder(self.highlighterTextButton, self.highlighterLineBackgroundButton)
        ColorSettings.setTabOrder(self.highlighterLineBackgroundButton, self.highlighterLineTextButton)

    def retranslateUi(self, ColorSettings):
        _translate = QtCore.QCoreApplication.translate
        ColorSettings.setWindowTitle(_translate("ColorSettings", "Highlighting, Colors, and Fonts"))
        self.label_8.setText(_translate("ColorSettings", "Highlighting"))
        self.enableHTextCheckBox.setText(_translate("ColorSettings", "Word"))
        self.enableHLineCheckBox.setText(_translate("ColorSettings", "Sentence"))
        self.followInsideParagraphCheckBox.setText(_translate("ColorSettings", "Follow Inside Paragraph"))
        self.label_6.setText(_translate("ColorSettings", "Content"))
        self.contentBackgroundButton.setText(_translate("ColorSettings", "Background"))
        self.contentTextButton.setText(_translate("ColorSettings", "Text"))
        self.label_4.setText(_translate("ColorSettings", "Highlighter Word"))
        self.highlighterBackgroundButton.setText(_translate("ColorSettings", "Background"))
        self.highlighterTextButton.setText(_translate("ColorSettings", "Text"))
        self.label_5.setText(_translate("ColorSettings", "Highlighter Sentence"))
        self.highlighterLineBackgroundButton.setText(_translate("ColorSettings", "Background"))
        self.highlighterLineTextButton.setText(_translate("ColorSettings", "Text"))
        self.label_9.setText(_translate("ColorSettings", "Font"))
        self.label_2.setText(_translate("ColorSettings", "Theme"))
        self.restoreButton.setToolTip(_translate("ColorSettings", "Restores settings to their default values"))
        self.restoreButton.setText(_translate("ColorSettings", "Restore to Default Settings"))

import resource_rc
