# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GraffeS.PC93667W7\git\central-access-reader\car/forms/mainwindow.ui'
#
# Created: Wed Jun 11 15:37:24 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 761)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/all/icons/CAR_About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.mainMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainMenuButton.setMaximumSize(QtCore.QSize(16777215, 38))
        self.mainMenuButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.mainMenuButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/classic/icons/menu_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainMenuButton.setIcon(icon1)
        self.mainMenuButton.setIconSize(QtCore.QSize(32, 32))
        self.mainMenuButton.setObjectName("mainMenuButton")
        self.horizontalLayout_3.addWidget(self.mainMenuButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(20)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.navigationTabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.navigationTabWidget.setUsesScrollButtons(False)
        self.navigationTabWidget.setObjectName("navigationTabWidget")
        self.bookmarksTab = QtWidgets.QWidget()
        self.bookmarksTab.setObjectName("bookmarksTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bookmarksTab)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bookmarksTreeView = QtWidgets.QTreeView(self.bookmarksTab)
        self.bookmarksTreeView.setHeaderHidden(True)
        self.bookmarksTreeView.setObjectName("bookmarksTreeView")
        self.verticalLayout.addWidget(self.bookmarksTreeView)
        self.navigationTabWidget.addTab(self.bookmarksTab, "")
        self.pagesTab = QtWidgets.QWidget()
        self.pagesTab.setObjectName("pagesTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pagesTab)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pagesTreeView = QtWidgets.QTreeView(self.pagesTab)
        self.pagesTreeView.setHeaderHidden(True)
        self.pagesTreeView.setObjectName("pagesTreeView")
        self.verticalLayout_2.addWidget(self.pagesTreeView)
        self.navigationTabWidget.addTab(self.pagesTab, "")
        self.verticalLayout_4.addWidget(self.navigationTabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bookmarkZoomInButton = QtWidgets.QPushButton(self.layoutWidget)
        self.bookmarkZoomInButton.setMaximumSize(QtCore.QSize(32, 32))
        self.bookmarkZoomInButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.bookmarkZoomInButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/classic/icons/magnify_add_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bookmarkZoomInButton.setIcon(icon2)
        self.bookmarkZoomInButton.setIconSize(QtCore.QSize(24, 24))
        self.bookmarkZoomInButton.setFlat(True)
        self.bookmarkZoomInButton.setObjectName("bookmarkZoomInButton")
        self.horizontalLayout_2.addWidget(self.bookmarkZoomInButton)
        self.bookmarkZoomOutButton = QtWidgets.QPushButton(self.layoutWidget)
        self.bookmarkZoomOutButton.setMaximumSize(QtCore.QSize(32, 32))
        self.bookmarkZoomOutButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.bookmarkZoomOutButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/classic/icons/magnify_minus_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bookmarkZoomOutButton.setIcon(icon3)
        self.bookmarkZoomOutButton.setIconSize(QtCore.QSize(24, 24))
        self.bookmarkZoomOutButton.setFlat(True)
        self.bookmarkZoomOutButton.setObjectName("bookmarkZoomOutButton")
        self.horizontalLayout_2.addWidget(self.bookmarkZoomOutButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.openDocumentButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.openDocumentButton.setMaximumSize(QtCore.QSize(60, 30))
        self.openDocumentButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.openDocumentButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/classic/icons/add_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openDocumentButton.setIcon(icon4)
        self.openDocumentButton.setIconSize(QtCore.QSize(24, 24))
        self.openDocumentButton.setFlat(True)
        self.openDocumentButton.setObjectName("openDocumentButton")
        self.verticalLayout_3.addWidget(self.openDocumentButton)
        self.controlPanel = QtWidgets.QFrame(self.layoutWidget1)
        self.controlPanel.setMaximumSize(QtCore.QSize(62, 16777215))
        self.controlPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlPanel.setLineWidth(0)
        self.controlPanel.setObjectName("controlPanel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.controlPanel)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.playButton = QtWidgets.QPushButton(self.controlPanel)
        self.playButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.playButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/classic/icons/play_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon5)
        self.playButton.setIconSize(QtCore.QSize(70, 70))
        self.playButton.setFlat(True)
        self.playButton.setObjectName("playButton")
        self.verticalLayout_7.addWidget(self.playButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.speechSettingsButton = QtWidgets.QPushButton(self.controlPanel)
        self.speechSettingsButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.speechSettingsButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/classic/icons/speech_settings_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speechSettingsButton.setIcon(icon6)
        self.speechSettingsButton.setIconSize(QtCore.QSize(70, 70))
        self.speechSettingsButton.setCheckable(True)
        self.speechSettingsButton.setFlat(True)
        self.speechSettingsButton.setObjectName("speechSettingsButton")
        self.verticalLayout_7.addWidget(self.speechSettingsButton)
        self.colorSettingsButton = QtWidgets.QPushButton(self.controlPanel)
        self.colorSettingsButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.colorSettingsButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/classic/icons/color_settings_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorSettingsButton.setIcon(icon7)
        self.colorSettingsButton.setIconSize(QtCore.QSize(70, 70))
        self.colorSettingsButton.setCheckable(True)
        self.colorSettingsButton.setFlat(True)
        self.colorSettingsButton.setObjectName("colorSettingsButton")
        self.verticalLayout_7.addWidget(self.colorSettingsButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem3)
        self.saveToMP3Button = QtWidgets.QPushButton(self.controlPanel)
        self.saveToMP3Button.setMaximumSize(QtCore.QSize(16777215, 60))
        self.saveToMP3Button.setFocusPolicy(QtCore.Qt.TabFocus)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/classic/icons/export_mp3_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveToMP3Button.setIcon(icon8)
        self.saveToMP3Button.setIconSize(QtCore.QSize(70, 70))
        self.saveToMP3Button.setFlat(True)
        self.saveToMP3Button.setObjectName("saveToMP3Button")
        self.verticalLayout_7.addWidget(self.saveToMP3Button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem4)
        self.zoomInButton = QtWidgets.QPushButton(self.controlPanel)
        self.zoomInButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zoomInButton.setFont(font)
        self.zoomInButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.zoomInButton.setIcon(icon2)
        self.zoomInButton.setIconSize(QtCore.QSize(70, 70))
        self.zoomInButton.setFlat(True)
        self.zoomInButton.setObjectName("zoomInButton")
        self.verticalLayout_7.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.controlPanel)
        self.zoomOutButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zoomOutButton.setFont(font)
        self.zoomOutButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.zoomOutButton.setIcon(icon3)
        self.zoomOutButton.setIconSize(QtCore.QSize(70, 70))
        self.zoomOutButton.setFlat(True)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.verticalLayout_7.addWidget(self.zoomOutButton)
        self.zoomResetButton = QtWidgets.QPushButton(self.controlPanel)
        self.zoomResetButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.zoomResetButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/classic/icons/magnify_reset_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomResetButton.setIcon(icon9)
        self.zoomResetButton.setIconSize(QtCore.QSize(70, 70))
        self.zoomResetButton.setFlat(True)
        self.zoomResetButton.setObjectName("zoomResetButton")
        self.verticalLayout_7.addWidget(self.zoomResetButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.splitterButton = QtWidgets.QPushButton(self.controlPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterButton.sizePolicy().hasHeightForWidth())
        self.splitterButton.setSizePolicy(sizePolicy)
        self.splitterButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.splitterButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.splitterButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/classic/icons/sidebar_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.splitterButton.setIcon(icon10)
        self.splitterButton.setIconSize(QtCore.QSize(70, 70))
        self.splitterButton.setCheckable(True)
        self.splitterButton.setChecked(True)
        self.splitterButton.setFlat(True)
        self.splitterButton.setObjectName("splitterButton")
        self.verticalLayout_7.addWidget(self.splitterButton)
        self.verticalLayout_3.addWidget(self.controlPanel)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.documentTabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        self.documentTabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.documentTabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.documentTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.documentTabWidget.setUsesScrollButtons(True)
        self.documentTabWidget.setDocumentMode(False)
        self.documentTabWidget.setTabsClosable(True)
        self.documentTabWidget.setMovable(True)
        self.documentTabWidget.setObjectName("documentTabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.documentTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.documentTabWidget.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.documentTabWidget)
        self.updateDownloadProgress = DownloadProgressWidget(self.layoutWidget1)
        self.updateDownloadProgress.setObjectName("updateDownloadProgress")
        self.verticalLayout_5.addWidget(self.updateDownloadProgress)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1168, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuFunction = QtWidgets.QMenu(self.menuBar)
        self.menuFunction.setObjectName("menuFunction")
        self.menuMP3 = QtWidgets.QMenu(self.menuBar)
        self.menuMP3.setObjectName("menuMP3")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuMathML = QtWidgets.QMenu(self.menuBar)
        self.menuMathML.setObjectName("menuMathML")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Docx = QtWidgets.QAction(MainWindow)
        self.actionOpen_Docx.setObjectName("actionOpen_Docx")
        self.actionOpen_Pattern_Editor = QtWidgets.QAction(MainWindow)
        self.actionOpen_Pattern_Editor.setObjectName("actionOpen_Pattern_Editor")
        self.actionShow_All_MathML = QtWidgets.QAction(MainWindow)
        self.actionShow_All_MathML.setObjectName("actionShow_All_MathML")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/application_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon11)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/help_contents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTutorial.setIcon(icon12)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/help_about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon13)
        self.actionAbout.setObjectName("actionAbout")
        self.actionReport_a_Bug = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/report_bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport_a_Bug.setIcon(icon14)
        self.actionReport_a_Bug.setObjectName("actionReport_a_Bug")
        self.actionTake_A_Survey = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/spread.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTake_A_Survey.setIcon(icon15)
        self.actionTake_A_Survey.setObjectName("actionTake_A_Survey")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon16)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon17)
        self.actionStop.setObjectName("actionStop")
        self.actionSave_Selection_to_MP3 = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/text_speak.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Selection_to_MP3.setIcon(icon18)
        self.actionSave_Selection_to_MP3.setObjectName("actionSave_Selection_to_MP3")
        self.actionSave_All_to_MP3 = QtWidgets.QAction(MainWindow)
        self.actionSave_All_to_MP3.setIcon(icon18)
        self.actionSave_All_to_MP3.setObjectName("actionSave_All_to_MP3")
        self.actionHighlights_Colors_and_Fonts = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/color_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHighlights_Colors_and_Fonts.setIcon(icon19)
        self.actionHighlights_Colors_and_Fonts.setObjectName("actionHighlights_Colors_and_Fonts")
        self.actionSpeech = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/system_config_services.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpeech.setIcon(icon20)
        self.actionSpeech.setObjectName("actionSpeech")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/icons/zoom_in_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon21)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/icons/zoom_out_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon22)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionReset_Zoom = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/icons/zoom_fit_best_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_Zoom.setIcon(icon23)
        self.actionReset_Zoom.setObjectName("actionReset_Zoom")
        self.actionIncrease_Volume = QtWidgets.QAction(MainWindow)
        self.actionIncrease_Volume.setObjectName("actionIncrease_Volume")
        self.actionDecrease_Volume = QtWidgets.QAction(MainWindow)
        self.actionDecrease_Volume.setObjectName("actionDecrease_Volume")
        self.actionIncrease_Rate = QtWidgets.QAction(MainWindow)
        self.actionIncrease_Rate.setObjectName("actionIncrease_Rate")
        self.actionDecrease_Rate = QtWidgets.QAction(MainWindow)
        self.actionDecrease_Rate.setObjectName("actionDecrease_Rate")
        self.actionEntire_Document = QtWidgets.QAction(MainWindow)
        self.actionEntire_Document.setIcon(icon18)
        self.actionEntire_Document.setObjectName("actionEntire_Document")
        self.actionCurrent_Selection = QtWidgets.QAction(MainWindow)
        self.actionCurrent_Selection.setIcon(icon18)
        self.actionCurrent_Selection.setObjectName("actionCurrent_Selection")
        self.actionBy_Page = QtWidgets.QAction(MainWindow)
        self.actionBy_Page.setIcon(icon18)
        self.actionBy_Page.setObjectName("actionBy_Page")
        self.actionExport_to_HTML = QtWidgets.QAction(MainWindow)
        self.actionExport_to_HTML.setObjectName("actionExport_to_HTML")
        self.actionClose_Document = QtWidgets.QAction(MainWindow)
        self.actionClose_Document.setObjectName("actionClose_Document")
        self.actionPaste_From_Clipboard = QtWidgets.QAction(MainWindow)
        self.actionPaste_From_Clipboard.setObjectName("actionPaste_From_Clipboard")
        self.actionBatch = QtWidgets.QAction(MainWindow)
        self.actionBatch.setObjectName("actionBatch")
        self.actionAnnouncements = QtWidgets.QAction(MainWindow)
        self.actionAnnouncements.setObjectName("actionAnnouncements")
        self.actionQuick_Start = QtWidgets.QAction(MainWindow)
        self.actionQuick_Start.setCheckable(True)
        self.actionQuick_Start.setObjectName("actionQuick_Start")
        self.menuFile.addAction(self.actionOpen_Docx)
        self.menuFile.addAction(self.actionClose_Document)
        self.menuFile.addAction(self.actionPaste_From_Clipboard)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_to_HTML)
        self.menuFile.addAction(self.actionBatch)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFunction.addAction(self.actionPlay)
        self.menuFunction.addAction(self.actionStop)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionZoom_In)
        self.menuFunction.addAction(self.actionZoom_Out)
        self.menuFunction.addAction(self.actionReset_Zoom)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionIncrease_Volume)
        self.menuFunction.addAction(self.actionDecrease_Volume)
        self.menuFunction.addAction(self.actionIncrease_Rate)
        self.menuFunction.addAction(self.actionDecrease_Rate)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionSearch)
        self.menuMP3.addAction(self.actionSave_All_to_MP3)
        self.menuMP3.addAction(self.actionSave_Selection_to_MP3)
        self.menuMP3.addSeparator()
        self.menuMP3.addAction(self.actionBy_Page)
        self.menuSettings.addAction(self.actionSpeech)
        self.menuSettings.addAction(self.actionHighlights_Colors_and_Fonts)
        self.menuMathML.addAction(self.actionOpen_Pattern_Editor)
        self.menuMathML.addAction(self.actionShow_All_MathML)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionAnnouncements)
        self.menuHelp.addAction(self.actionQuick_Start)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReport_a_Bug)
        self.menuHelp.addAction(self.actionTake_A_Survey)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuFunction.menuAction())
        self.menuBar.addAction(self.menuMP3.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuMathML.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.navigationTabWidget.setCurrentIndex(0)
        self.documentTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Central Access Reader"))
        self.mainMenuButton.setToolTip(_translate("MainWindow", "Main Menu"))
        self.navigationTabWidget.setTabText(self.navigationTabWidget.indexOf(self.bookmarksTab), _translate("MainWindow", "Headings"))
        self.navigationTabWidget.setTabText(self.navigationTabWidget.indexOf(self.pagesTab), _translate("MainWindow", "Pages"))
        self.bookmarkZoomInButton.setToolTip(_translate("MainWindow", "Zoom In"))
        self.bookmarkZoomOutButton.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.openDocumentButton.setToolTip(_translate("MainWindow", "Open Document"))
        self.playButton.setToolTip(_translate("MainWindow", "Start"))
        self.speechSettingsButton.setToolTip(_translate("MainWindow", "General Settings"))
        self.colorSettingsButton.setToolTip(_translate("MainWindow", "Color Settings"))
        self.saveToMP3Button.setToolTip(_translate("MainWindow", "Save All To MP3"))
        self.zoomInButton.setToolTip(_translate("MainWindow", "Zoom In"))
        self.zoomOutButton.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.zoomResetButton.setToolTip(_translate("MainWindow", "Reset Zoom"))
        self.splitterButton.setToolTip(_translate("MainWindow", "Show/Hide Navigation"))
        self.documentTabWidget.setTabText(self.documentTabWidget.indexOf(self.tab_3), _translate("MainWindow", "1701 Essentials of Mathematics"))
        self.documentTabWidget.setTabText(self.documentTabWidget.indexOf(self.tab_4), _translate("MainWindow", "1551 Ch 01 Statistics for the Behavorial Sciences"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFunction.setTitle(_translate("MainWindow", "Functions"))
        self.menuMP3.setTitle(_translate("MainWindow", "MP3"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuMathML.setTitle(_translate("MainWindow", "Math"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Docx.setText(_translate("MainWindow", "&Open Word Document"))
        self.actionOpen_Docx.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Pattern_Editor.setText(_translate("MainWindow", "&Math Library Development Environment"))
        self.actionShow_All_MathML.setText(_translate("MainWindow", "&Show All MathML..."))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionTutorial.setText(_translate("MainWindow", "&Tutorial"))
        self.actionTutorial.setShortcut(_translate("MainWindow", "Ctrl+Shift+H"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+Alt+H"))
        self.actionReport_a_Bug.setText(_translate("MainWindow", "Report a &Bug"))
        self.actionTake_A_Survey.setText(_translate("MainWindow", "Give Us &Feedback"))
        self.actionSearch.setText(_translate("MainWindow", "S&earch"))
        self.actionSearch.setToolTip(_translate("MainWindow", "Toggles the search bar on and off."))
        self.actionSearch.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionPlay.setText(_translate("MainWindow", "&Read"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionStop.setText(_translate("MainWindow", "&Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_Selection_to_MP3.setText(_translate("MainWindow", "Save &Selection"))
        self.actionSave_Selection_to_MP3.setShortcut(_translate("MainWindow", "Ctrl+Shift+M"))
        self.actionSave_All_to_MP3.setText(_translate("MainWindow", "Save &All"))
        self.actionSave_All_to_MP3.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionHighlights_Colors_and_Fonts.setText(_translate("MainWindow", "&Color"))
        self.actionHighlights_Colors_and_Fonts.setShortcut(_translate("MainWindow", "F2"))
        self.actionSpeech.setText(_translate("MainWindow", "&General"))
        self.actionSpeech.setShortcut(_translate("MainWindow", "F1"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionReset_Zoom.setText(_translate("MainWindow", "Reset Zoom"))
        self.actionReset_Zoom.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.actionIncrease_Volume.setText(_translate("MainWindow", "Increase Volume"))
        self.actionIncrease_Volume.setToolTip(_translate("MainWindow", "Increase Volume"))
        self.actionIncrease_Volume.setShortcut(_translate("MainWindow", "Ctrl+Up"))
        self.actionDecrease_Volume.setText(_translate("MainWindow", "Decrease Volume"))
        self.actionDecrease_Volume.setToolTip(_translate("MainWindow", "Decrease Volume"))
        self.actionDecrease_Volume.setShortcut(_translate("MainWindow", "Ctrl+Down"))
        self.actionIncrease_Rate.setText(_translate("MainWindow", "Increase Rate"))
        self.actionIncrease_Rate.setToolTip(_translate("MainWindow", "Increase Rate"))
        self.actionIncrease_Rate.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.actionDecrease_Rate.setText(_translate("MainWindow", "Decrease Rate"))
        self.actionDecrease_Rate.setToolTip(_translate("MainWindow", "Decrease Rate"))
        self.actionDecrease_Rate.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.actionEntire_Document.setText(_translate("MainWindow", "Entire Document"))
        self.actionCurrent_Selection.setText(_translate("MainWindow", "Current Selection"))
        self.actionBy_Page.setText(_translate("MainWindow", "Save By Page"))
        self.actionExport_to_HTML.setText(_translate("MainWindow", "&Export to HTML"))
        self.actionClose_Document.setText(_translate("MainWindow", "Close Document"))
        self.actionClose_Document.setToolTip(_translate("MainWindow", "Closes the current document."))
        self.actionClose_Document.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionPaste_From_Clipboard.setText(_translate("MainWindow", "Paste From Clipboard"))
        self.actionPaste_From_Clipboard.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionBatch.setText(_translate("MainWindow", "Batch"))
        self.actionAnnouncements.setText(_translate("MainWindow", "Announcements"))
        self.actionQuick_Start.setText(_translate("MainWindow", "Quick Start"))

from car.gui.download_progress import DownloadProgressWidget
import resource_rc
