# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GraffeS.PC93667W7\git\central-access-reader\car/forms/math_library_dev.ui'
#
# Created: Wed Jun 11 15:37:25 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MathLibraryDev(object):
    def setupUi(self, MathLibraryDev):
        MathLibraryDev.setObjectName("MathLibraryDev")
        MathLibraryDev.resize(1030, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/all/icons/CAR_About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MathLibraryDev.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MathLibraryDev)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.proseOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.proseOutput.setObjectName("proseOutput")
        self.horizontalLayout.addWidget(self.proseOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.libraryTabs = QtWidgets.QTabWidget(self.splitter)
        self.libraryTabs.setTabsClosable(True)
        self.libraryTabs.setMovable(True)
        self.libraryTabs.setObjectName("libraryTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.libraryTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.libraryTabs.addTab(self.tab_2, "")
        self.splitter2 = QtWidgets.QSplitter(self.splitter)
        self.splitter2.setOrientation(QtCore.Qt.Vertical)
        self.splitter2.setObjectName("splitter2")
        self.mathmlEditor = MathMLEditor(self.splitter2)
        self.mathmlEditor.setMinimumSize(QtCore.QSize(200, 200))
        self.mathmlEditor.setObjectName("mathmlEditor")
        self.layoutWidget = QtWidgets.QWidget(self.splitter2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.expandStagesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.expandStagesButton.setObjectName("expandStagesButton")
        self.horizontalLayout_2.addWidget(self.expandStagesButton)
        self.collapseStagesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.collapseStagesButton.setObjectName("collapseStagesButton")
        self.horizontalLayout_2.addWidget(self.collapseStagesButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stagesView = QtWidgets.QTreeView(self.layoutWidget)
        self.stagesView.setObjectName("stagesView")
        self.stagesView.header().setVisible(False)
        self.verticalLayout.addWidget(self.stagesView)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_3.setStretch(1, 1)
        MathLibraryDev.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MathLibraryDev)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInstalled_Libraries = QtWidgets.QMenu(self.menuFile)
        self.menuInstalled_Libraries.setObjectName("menuInstalled_Libraries")
        self.menuMathML = QtWidgets.QMenu(self.menubar)
        self.menuMathML.setObjectName("menuMathML")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MathLibraryDev.setMenuBar(self.menubar)
        self.actionNew_Library = QtWidgets.QAction(MathLibraryDev)
        self.actionNew_Library.setObjectName("actionNew_Library")
        self.actionOpen_Library = QtWidgets.QAction(MathLibraryDev)
        self.actionOpen_Library.setObjectName("actionOpen_Library")
        self.actionNew_Pattern = QtWidgets.QAction(MathLibraryDev)
        self.actionNew_Pattern.setObjectName("actionNew_Pattern")
        self.actionOpen_Pattern = QtWidgets.QAction(MathLibraryDev)
        self.actionOpen_Pattern.setObjectName("actionOpen_Pattern")
        self.actionSave = QtWidgets.QAction(MathLibraryDev)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MathLibraryDev)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MathLibraryDev)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFrom_Clipboard = QtWidgets.QAction(MathLibraryDev)
        self.actionFrom_Clipboard.setObjectName("actionFrom_Clipboard")
        self.actionThings = QtWidgets.QAction(MathLibraryDev)
        self.actionThings.setObjectName("actionThings")
        self.actionExport = QtWidgets.QAction(MathLibraryDev)
        self.actionExport.setObjectName("actionExport")
        self.actionContents = QtWidgets.QAction(MathLibraryDev)
        self.actionContents.setObjectName("actionContents")
        self.menuInstalled_Libraries.addAction(self.actionThings)
        self.menuFile.addAction(self.actionNew_Library)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuInstalled_Libraries.menuAction())
        self.menuFile.addAction(self.actionOpen_Library)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_Pattern)
        self.menuFile.addAction(self.actionOpen_Pattern)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuMathML.addAction(self.actionFrom_Clipboard)
        self.menuHelp.addAction(self.actionContents)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMathML.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MathLibraryDev)
        self.libraryTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MathLibraryDev)

    def retranslateUi(self, MathLibraryDev):
        _translate = QtCore.QCoreApplication.translate
        MathLibraryDev.setWindowTitle(_translate("MathLibraryDev", "Math Library Development Environment"))
        self.runButton.setText(_translate("MathLibraryDev", "Run"))
        self.libraryTabs.setTabText(self.libraryTabs.indexOf(self.tab), _translate("MathLibraryDev", "Tab 1"))
        self.libraryTabs.setTabText(self.libraryTabs.indexOf(self.tab_2), _translate("MathLibraryDev", "Tab 2"))
        self.label_2.setText(_translate("MathLibraryDev", "Stages:"))
        self.expandStagesButton.setText(_translate("MathLibraryDev", "Expand"))
        self.collapseStagesButton.setText(_translate("MathLibraryDev", "Collapse"))
        self.menuFile.setTitle(_translate("MathLibraryDev", "File"))
        self.menuInstalled_Libraries.setTitle(_translate("MathLibraryDev", "Open Library"))
        self.menuMathML.setTitle(_translate("MathLibraryDev", "MathML"))
        self.menuHelp.setTitle(_translate("MathLibraryDev", "Help"))
        self.actionNew_Library.setText(_translate("MathLibraryDev", "New Library"))
        self.actionNew_Library.setShortcut(_translate("MathLibraryDev", "Ctrl+Shift+N"))
        self.actionOpen_Library.setText(_translate("MathLibraryDev", "Open Library From File"))
        self.actionOpen_Library.setShortcut(_translate("MathLibraryDev", "Ctrl+Shift+O"))
        self.actionNew_Pattern.setText(_translate("MathLibraryDev", "New Pattern"))
        self.actionNew_Pattern.setShortcut(_translate("MathLibraryDev", "Ctrl+N"))
        self.actionOpen_Pattern.setText(_translate("MathLibraryDev", "Open Pattern"))
        self.actionOpen_Pattern.setShortcut(_translate("MathLibraryDev", "Ctrl+O"))
        self.actionSave.setText(_translate("MathLibraryDev", "Save"))
        self.actionSave.setShortcut(_translate("MathLibraryDev", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MathLibraryDev", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MathLibraryDev", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MathLibraryDev", "Quit"))
        self.actionFrom_Clipboard.setText(_translate("MathLibraryDev", "From Clipboard"))
        self.actionFrom_Clipboard.setShortcut(_translate("MathLibraryDev", "Ctrl+Shift+V"))
        self.actionThings.setText(_translate("MathLibraryDev", "Things"))
        self.actionExport.setText(_translate("MathLibraryDev", "Export..."))
        self.actionContents.setText(_translate("MathLibraryDev", "Guide"))

from car.gui.mathml_editor import MathMLEditor
import resource_rc
