# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GraffeS.PC93667W7\git\central-access-reader\car/forms/speech_settings.ui'
#
# Created: Wed Jun 11 15:37:27 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpeechSettings(object):
    def setupUi(self, SpeechSettings):
        SpeechSettings.setObjectName("SpeechSettings")
        SpeechSettings.resize(337, 841)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/classic/icons/speech_settings_classic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpeechSettings.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SpeechSettings)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(SpeechSettings)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 335, 816))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setSpacing(40)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.rateSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rateSlider.sizePolicy().hasHeightForWidth())
        self.rateSlider.setSizePolicy(sizePolicy)
        self.rateSlider.setMinimum(0)
        self.rateSlider.setMaximum(100)
        self.rateSlider.setProperty("value", 50)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.rateSlider.setTickInterval(10)
        self.rateSlider.setObjectName("rateSlider")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rateSlider)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.volumeSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.volumeSlider.setTickInterval(10)
        self.volumeSlider.setObjectName("volumeSlider")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.volumeSlider)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pauseSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseSlider.sizePolicy().hasHeightForWidth())
        self.pauseSlider.setSizePolicy(sizePolicy)
        self.pauseSlider.setMaximum(10)
        self.pauseSlider.setPageStep(1)
        self.pauseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pauseSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.pauseSlider.setTickInterval(1)
        self.pauseSlider.setObjectName("pauseSlider")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pauseSlider)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("font-size: 16pt;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.voiceComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.voiceComboBox.setEditable(False)
        self.voiceComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.voiceComboBox.setObjectName("voiceComboBox")
        self.verticalLayout_5.addWidget(self.voiceComboBox)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("font-size: 16pt;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.mathLibraryDisplay = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.mathLibraryDisplay.setStyleSheet("border-width: 5px;")
        self.mathLibraryDisplay.setReadOnly(True)
        self.mathLibraryDisplay.setObjectName("mathLibraryDisplay")
        self.verticalLayout_2.addWidget(self.mathLibraryDisplay)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.languageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.languageLabel.setObjectName("languageLabel")
        self.horizontalLayout_2.addWidget(self.languageLabel)
        self.mathLanguageCombo = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.mathLanguageCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.mathLanguageCombo.setObjectName("mathLanguageCombo")
        self.horizontalLayout_2.addWidget(self.mathLanguageCombo)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.libraryLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.libraryLabel.setObjectName("libraryLabel")
        self.horizontalLayout.addWidget(self.libraryLabel)
        self.mathAddButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.mathAddButton.setObjectName("mathAddButton")
        self.horizontalLayout.addWidget(self.mathAddButton)
        self.mathRemoveButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.mathRemoveButton.setObjectName("mathRemoveButton")
        self.horizontalLayout.addWidget(self.mathRemoveButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.openMLDEButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.openMLDEButton.setObjectName("openMLDEButton")
        self.horizontalLayout.addWidget(self.openMLDEButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mathLibraryTree = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        self.mathLibraryTree.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mathLibraryTree.setFont(font)
        self.mathLibraryTree.setObjectName("mathLibraryTree")
        self.mathLibraryTree.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.mathLibraryTree)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("font-size: 16pt;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.imageTagCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.imageTagCheckBox.setObjectName("imageTagCheckBox")
        self.verticalLayout.addWidget(self.imageTagCheckBox)
        self.mathTagCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.mathTagCheckBox.setObjectName("mathTagCheckBox")
        self.verticalLayout.addWidget(self.mathTagCheckBox)
        self.ignoreAltTextCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ignoreAltTextCheckBox.setObjectName("ignoreAltTextCheckBox")
        self.verticalLayout.addWidget(self.ignoreAltTextCheckBox)
        self.tableOfContentsCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.tableOfContentsCheckBox.setObjectName("tableOfContentsCheckBox")
        self.verticalLayout.addWidget(self.tableOfContentsCheckBox)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.verticalLayout_9.setStretch(4, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.restoreButton = QtWidgets.QPushButton(SpeechSettings)
        self.restoreButton.setObjectName("restoreButton")
        self.verticalLayout_3.addWidget(self.restoreButton)

        self.retranslateUi(SpeechSettings)
        QtCore.QMetaObject.connectSlotsByName(SpeechSettings)

    def retranslateUi(self, SpeechSettings):
        _translate = QtCore.QCoreApplication.translate
        SpeechSettings.setWindowTitle(_translate("SpeechSettings", "General"))
        self.label_7.setText(_translate("SpeechSettings", "Rate"))
        self.rateSlider.setToolTip(_translate("SpeechSettings", "Words per minute slider (rate)"))
        self.label_2.setText(_translate("SpeechSettings", "Volume"))
        self.volumeSlider.setToolTip(_translate("SpeechSettings", "Volume slider"))
        self.label_6.setText(_translate("SpeechSettings", "Pause Length"))
        self.label_3.setText(_translate("SpeechSettings", "Voices"))
        self.voiceComboBox.setToolTip(_translate("SpeechSettings", "Drop down box for selecting the voice"))
        self.label_5.setText(_translate("SpeechSettings", "Math"))
        self.mathLibraryDisplay.setPlaceholderText(_translate("SpeechSettings", "<current math library>"))
        self.languageLabel.setText(_translate("SpeechSettings", "Language:"))
        self.libraryLabel.setText(_translate("SpeechSettings", "Library:"))
        self.mathAddButton.setToolTip(_translate("SpeechSettings", "Adds math library from file."))
        self.mathAddButton.setText(_translate("SpeechSettings", "+"))
        self.mathRemoveButton.setToolTip(_translate("SpeechSettings", "Removes current math library."))
        self.mathRemoveButton.setText(_translate("SpeechSettings", "-"))
        self.openMLDEButton.setText(_translate("SpeechSettings", "Open MLDE"))
        self.label_4.setText(_translate("SpeechSettings", "Tag"))
        self.imageTagCheckBox.setText(_translate("SpeechSettings", "Image"))
        self.mathTagCheckBox.setText(_translate("SpeechSettings", "Math"))
        self.ignoreAltTextCheckBox.setText(_translate("SpeechSettings", "Ignore Alternate Text"))
        self.tableOfContentsCheckBox.setText(_translate("SpeechSettings", "Add TOC To HTML"))
        self.restoreButton.setToolTip(_translate("SpeechSettings", "Restores settings to default values"))
        self.restoreButton.setText(_translate("SpeechSettings", "Restore to Default Settings"))

import resource_rc
