# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W:\Documents\Special Projects\Graffe, Spencer\workspace2\nifty-prose-articulator\src\script_test_environment\forms/mainwindow.ui'
#
# Created: Tue Apr 02 08:16:00 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(692, 404)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(15)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.resetButton = QtGui.QPushButton(self.layoutWidget)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout_2.addWidget(self.resetButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.documentView = QtWebKit.QWebView(self.layoutWidget)
        self.documentView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.documentView.setObjectName(_fromUtf8("documentView"))
        self.verticalLayout.addWidget(self.documentView)
        self.verticalLayout.setStretch(1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.run1Button = QtGui.QPushButton(self.layoutWidget1)
        self.run1Button.setObjectName(_fromUtf8("run1Button"))
        self.horizontalLayout.addWidget(self.run1Button)
        self.commandLine1 = QtGui.QLineEdit(self.layoutWidget1)
        self.commandLine1.setObjectName(_fromUtf8("commandLine1"))
        self.horizontalLayout.addWidget(self.commandLine1)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.run2Button = QtGui.QPushButton(self.layoutWidget1)
        self.run2Button.setObjectName(_fromUtf8("run2Button"))
        self.horizontalLayout.addWidget(self.run2Button)
        self.commandLine2 = QtGui.QLineEdit(self.layoutWidget1)
        self.commandLine2.setObjectName(_fromUtf8("commandLine2"))
        self.horizontalLayout.addWidget(self.commandLine2)
        self.line_2 = QtGui.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.run3Button = QtGui.QPushButton(self.layoutWidget1)
        self.run3Button.setObjectName(_fromUtf8("run3Button"))
        self.horizontalLayout.addWidget(self.run3Button)
        self.commandLine3 = QtGui.QLineEdit(self.layoutWidget1)
        self.commandLine3.setObjectName(_fromUtf8("commandLine3"))
        self.horizontalLayout.addWidget(self.commandLine3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.javascriptTabs = QtGui.QTabWidget(self.layoutWidget1)
        self.javascriptTabs.setTabsClosable(True)
        self.javascriptTabs.setMovable(True)
        self.javascriptTabs.setObjectName(_fromUtf8("javascriptTabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.javascriptTabs.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.javascriptTabs.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.javascriptTabs)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Docx = QtGui.QAction(MainWindow)
        self.actionOpen_Docx.setObjectName(_fromUtf8("actionOpen_Docx"))
        self.actionOpen_Javascript = QtGui.QAction(MainWindow)
        self.actionOpen_Javascript.setObjectName(_fromUtf8("actionOpen_Javascript"))
        self.actionSave_Current = QtGui.QAction(MainWindow)
        self.actionSave_Current.setObjectName(_fromUtf8("actionSave_Current"))
        self.actionSave_All = QtGui.QAction(MainWindow)
        self.actionSave_All.setObjectName(_fromUtf8("actionSave_All"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew_Script = QtGui.QAction(MainWindow)
        self.actionNew_Script.setObjectName(_fromUtf8("actionNew_Script"))
        self.menuFile.addAction(self.actionNew_Script)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Docx)
        self.menuFile.addAction(self.actionOpen_Javascript)
        self.menuFile.addAction(self.actionSave_Current)
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Javascript Test Environment", None))
        self.label.setText(_translate("MainWindow", "Document:", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.run1Button.setText(_translate("MainWindow", "Run 1", None))
        self.run2Button.setText(_translate("MainWindow", "Run 2", None))
        self.run3Button.setText(_translate("MainWindow", "Run 3", None))
        self.javascriptTabs.setTabText(self.javascriptTabs.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.javascriptTabs.setTabText(self.javascriptTabs.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen_Docx.setText(_translate("MainWindow", "Open Docx", None))
        self.actionOpen_Docx.setShortcut(_translate("MainWindow", "Ctrl+Shift+O", None))
        self.actionOpen_Javascript.setText(_translate("MainWindow", "Open Script", None))
        self.actionOpen_Javascript.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave_Current.setText(_translate("MainWindow", "Save Current", None))
        self.actionSave_Current.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_All.setText(_translate("MainWindow", "Save All", None))
        self.actionSave_All.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionNew_Script.setText(_translate("MainWindow", "New Script", None))
        self.actionNew_Script.setShortcut(_translate("MainWindow", "Ctrl+N", None))

from PyQt4 import QtWebKit
