# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/atrctech/Desktop/workspace/NiftyProseArticulator/src/forms/color_settings.ui'
#
# Created: Fri Sep 13 14:31:10 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ColorSettings(object):
    def setupUi(self, ColorSettings):
        ColorSettings.setObjectName("ColorSettings")
        ColorSettings.resize(463, 301)
        font = QtGui.QFont()
        font.setPointSize(12)
        ColorSettings.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/color_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ColorSettings.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ColorSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtGui.QLabel(ColorSettings)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.line_5 = QtGui.QFrame(ColorSettings)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(ColorSettings)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtGui.QLabel(ColorSettings)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contentBackgroundButton = QtGui.QPushButton(ColorSettings)
        self.contentBackgroundButton.setObjectName("contentBackgroundButton")
        self.horizontalLayout_3.addWidget(self.contentBackgroundButton)
        self.contentTextButton = QtGui.QPushButton(ColorSettings)
        self.contentTextButton.setObjectName("contentTextButton")
        self.horizontalLayout_3.addWidget(self.contentTextButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtGui.QLabel(ColorSettings)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.highlighterBackgroundButton = QtGui.QPushButton(ColorSettings)
        self.highlighterBackgroundButton.setObjectName("highlighterBackgroundButton")
        self.horizontalLayout_4.addWidget(self.highlighterBackgroundButton)
        self.highlighterTextButton = QtGui.QPushButton(ColorSettings)
        self.highlighterTextButton.setObjectName("highlighterTextButton")
        self.horizontalLayout_4.addWidget(self.highlighterTextButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_5 = QtGui.QLabel(ColorSettings)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.highlighterLineBackgroundButton = QtGui.QPushButton(ColorSettings)
        self.highlighterLineBackgroundButton.setObjectName("highlighterLineBackgroundButton")
        self.horizontalLayout_5.addWidget(self.highlighterLineBackgroundButton)
        self.highlighterLineTextButton = QtGui.QPushButton(ColorSettings)
        self.highlighterLineTextButton.setObjectName("highlighterLineTextButton")
        self.horizontalLayout_5.addWidget(self.highlighterLineTextButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.formLayout, 1, 2, 1, 1)
        self.line_4 = QtGui.QFrame(ColorSettings)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 1, 1, 1)
        self.line_3 = QtGui.QFrame(ColorSettings)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(ColorSettings)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.fontComboBox = QtGui.QFontComboBox(ColorSettings)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout_3.addWidget(self.fontComboBox, 2, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.enableHTextCheckBox = QtGui.QCheckBox(ColorSettings)
        self.enableHTextCheckBox.setObjectName("enableHTextCheckBox")
        self.verticalLayout.addWidget(self.enableHTextCheckBox)
        self.enableHLineCheckBox = QtGui.QCheckBox(ColorSettings)
        self.enableHLineCheckBox.setObjectName("enableHLineCheckBox")
        self.verticalLayout.addWidget(self.enableHLineCheckBox)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.restoreButton = QtGui.QPushButton(ColorSettings)
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout.addWidget(self.restoreButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.previewButton = QtGui.QPushButton(ColorSettings)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout.addWidget(self.previewButton)
        self.applyButton = QtGui.QPushButton(ColorSettings)
        self.applyButton.setIconSize(QtCore.QSize(50, 50))
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ColorSettings)
        QtCore.QMetaObject.connectSlotsByName(ColorSettings)
        ColorSettings.setTabOrder(self.enableHTextCheckBox, self.enableHLineCheckBox)
        ColorSettings.setTabOrder(self.enableHLineCheckBox, self.contentBackgroundButton)
        ColorSettings.setTabOrder(self.contentBackgroundButton, self.contentTextButton)
        ColorSettings.setTabOrder(self.contentTextButton, self.highlighterBackgroundButton)
        ColorSettings.setTabOrder(self.highlighterBackgroundButton, self.highlighterTextButton)
        ColorSettings.setTabOrder(self.highlighterTextButton, self.highlighterLineBackgroundButton)
        ColorSettings.setTabOrder(self.highlighterLineBackgroundButton, self.highlighterLineTextButton)
        ColorSettings.setTabOrder(self.highlighterLineTextButton, self.fontComboBox)
        ColorSettings.setTabOrder(self.fontComboBox, self.restoreButton)
        ColorSettings.setTabOrder(self.restoreButton, self.previewButton)
        ColorSettings.setTabOrder(self.previewButton, self.applyButton)

    def retranslateUi(self, ColorSettings):
        ColorSettings.setWindowTitle(QtGui.QApplication.translate("ColorSettings", "Highlighting, Colors, and Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ColorSettings", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ColorSettings", "Colors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ColorSettings", "Content:", None, QtGui.QApplication.UnicodeUTF8))
        self.contentBackgroundButton.setText(QtGui.QApplication.translate("ColorSettings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTextButton.setText(QtGui.QApplication.translate("ColorSettings", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ColorSettings", "Highlighter Word:", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterBackgroundButton.setText(QtGui.QApplication.translate("ColorSettings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterTextButton.setText(QtGui.QApplication.translate("ColorSettings", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ColorSettings", "Highlighter Sentence:", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterLineBackgroundButton.setText(QtGui.QApplication.translate("ColorSettings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterLineTextButton.setText(QtGui.QApplication.translate("ColorSettings", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ColorSettings", "Highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.enableHTextCheckBox.setText(QtGui.QApplication.translate("ColorSettings", "Word", None, QtGui.QApplication.UnicodeUTF8))
        self.enableHLineCheckBox.setText(QtGui.QApplication.translate("ColorSettings", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setToolTip(QtGui.QApplication.translate("ColorSettings", "Restores settings to what they were when you opened the window", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setText(QtGui.QApplication.translate("ColorSettings", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("ColorSettings", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setToolTip(QtGui.QApplication.translate("ColorSettings", "Apply new speech settings", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("ColorSettings", "Apply", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
