# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/atrctech/Desktop/workspace/NiftyProseArticulator/src/forms/settings.ui'
#
# Created: Fri Sep 13 14:31:12 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(614, 473)
        font = QtGui.QFont()
        font.setPointSize(12)
        Settings.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.speechTab = QtGui.QWidget()
        self.speechTab.setObjectName("speechTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.speechTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.speechTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.speechTab)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.speechTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.rateSlider = QtGui.QSlider(self.speechTab)
        self.rateSlider.setMinimumSize(QtCore.QSize(201, 0))
        self.rateSlider.setMinimum(100)
        self.rateSlider.setMaximum(300)
        self.rateSlider.setProperty("value", 200)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setObjectName("rateSlider")
        self.gridLayout.addWidget(self.rateSlider, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.speechTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.volumeSlider = QtGui.QSlider(self.speechTab)
        self.volumeSlider.setMinimumSize(QtCore.QSize(201, 0))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 99)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout.addWidget(self.volumeSlider, 1, 2, 1, 1)
        self.rateLabel = QtGui.QLabel(self.speechTab)
        self.rateLabel.setObjectName("rateLabel")
        self.gridLayout.addWidget(self.rateLabel, 0, 1, 1, 1)
        self.volumeLabel = QtGui.QLabel(self.speechTab)
        self.volumeLabel.setObjectName("volumeLabel")
        self.gridLayout.addWidget(self.volumeLabel, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.testSpeechText = QtGui.QPlainTextEdit(self.speechTab)
        self.testSpeechText.setObjectName("testSpeechText")
        self.horizontalLayout_2.addWidget(self.testSpeechText)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.testButton = QtGui.QPushButton(self.speechTab)
        self.testButton.setIconSize(QtCore.QSize(50, 50))
        self.testButton.setObjectName("testButton")
        self.verticalLayout_2.addWidget(self.testButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.speechTab, "")
        self.colorsTab = QtGui.QWidget()
        self.colorsTab.setObjectName("colorsTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.colorsTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtGui.QLabel(self.colorsTab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contentBackgroundButton = QtGui.QPushButton(self.colorsTab)
        self.contentBackgroundButton.setObjectName("contentBackgroundButton")
        self.horizontalLayout_3.addWidget(self.contentBackgroundButton)
        self.contentTextButton = QtGui.QPushButton(self.colorsTab)
        self.contentTextButton.setObjectName("contentTextButton")
        self.horizontalLayout_3.addWidget(self.contentTextButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtGui.QLabel(self.colorsTab)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.highlighterBackgroundButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterBackgroundButton.setObjectName("highlighterBackgroundButton")
        self.horizontalLayout_4.addWidget(self.highlighterBackgroundButton)
        self.highlighterTextButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterTextButton.setObjectName("highlighterTextButton")
        self.horizontalLayout_4.addWidget(self.highlighterTextButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_5 = QtGui.QLabel(self.colorsTab)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.highlighterLineBackgroundButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterLineBackgroundButton.setObjectName("highlighterLineBackgroundButton")
        self.horizontalLayout_5.addWidget(self.highlighterLineBackgroundButton)
        self.highlighterLineTextButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterLineTextButton.setObjectName("highlighterLineTextButton")
        self.horizontalLayout_5.addWidget(self.highlighterLineTextButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.formLayout, 1, 2, 1, 1)
        self.enableHighlightCheckbox = QtGui.QCheckBox(self.colorsTab)
        self.enableHighlightCheckbox.setObjectName("enableHighlightCheckbox")
        self.gridLayout_3.addWidget(self.enableHighlightCheckbox, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.colorsTab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.colorsTab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.colorsTab)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.colorsTab)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.colorsTab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.colorsTab)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 2, 1, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSpacing(8)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtGui.QLabel(self.colorsTab)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.colorsTab)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.colorsTab)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.colorsTab)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.colorsTab)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.paragraphFontButton = QtGui.QPushButton(self.colorsTab)
        self.paragraphFontButton.setObjectName("paragraphFontButton")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.paragraphFontButton)
        self.header1FontButton = QtGui.QPushButton(self.colorsTab)
        self.header1FontButton.setObjectName("header1FontButton")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.header1FontButton)
        self.header2FontButton = QtGui.QPushButton(self.colorsTab)
        self.header2FontButton.setObjectName("header2FontButton")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.header2FontButton)
        self.header3FontButton = QtGui.QPushButton(self.colorsTab)
        self.header3FontButton.setObjectName("header3FontButton")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.header3FontButton)
        self.header4FontButton = QtGui.QPushButton(self.colorsTab)
        self.header4FontButton.setObjectName("header4FontButton")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.header4FontButton)
        self.gridLayout_3.addLayout(self.formLayout_2, 2, 2, 1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem4 = QtGui.QSpacerItem(20, 11, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.colorsTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.restoreButton = QtGui.QPushButton(Settings)
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout.addWidget(self.restoreButton)
        self.applyButton = QtGui.QPushButton(Settings)
        self.applyButton.setIconSize(QtCore.QSize(50, 50))
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "Words Per Minute:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("Settings", "Drop down box for selecting the voice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Settings", "Volume:", None, QtGui.QApplication.UnicodeUTF8))
        self.rateSlider.setToolTip(QtGui.QApplication.translate("Settings", "Words per minute slider (rate)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Settings", "Voices:", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeSlider.setToolTip(QtGui.QApplication.translate("Settings", "Volume slider", None, QtGui.QApplication.UnicodeUTF8))
        self.rateLabel.setText(QtGui.QApplication.translate("Settings", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeLabel.setText(QtGui.QApplication.translate("Settings", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.testSpeechText.setToolTip(QtGui.QApplication.translate("Settings", "The text entered here is used when the test speech button is pressed", None, QtGui.QApplication.UnicodeUTF8))
        self.testSpeechText.setPlainText(QtGui.QApplication.translate("Settings", "This is a test of the current text to speech settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setToolTip(QtGui.QApplication.translate("Settings", "Apply and test current speech settings", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("Settings", "Test Speech", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.speechTab), QtGui.QApplication.translate("Settings", "Speech", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Settings", "Content:", None, QtGui.QApplication.UnicodeUTF8))
        self.contentBackgroundButton.setText(QtGui.QApplication.translate("Settings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTextButton.setText(QtGui.QApplication.translate("Settings", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Settings", "Highlighter Text:", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterBackgroundButton.setText(QtGui.QApplication.translate("Settings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterTextButton.setText(QtGui.QApplication.translate("Settings", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Settings", "Highlighter Line:", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterLineBackgroundButton.setText(QtGui.QApplication.translate("Settings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.highlighterLineTextButton.setText(QtGui.QApplication.translate("Settings", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.enableHighlightCheckbox.setText(QtGui.QApplication.translate("Settings", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Settings", "Colors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Settings", "Highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Settings", "Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Settings", "Paragraph:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Settings", "Header 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Settings", "Header 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Settings", "Header 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Settings", "Header 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.paragraphFontButton.setText(QtGui.QApplication.translate("Settings", "Paragraph Font", None, QtGui.QApplication.UnicodeUTF8))
        self.header1FontButton.setText(QtGui.QApplication.translate("Settings", "Header 1 Font", None, QtGui.QApplication.UnicodeUTF8))
        self.header2FontButton.setText(QtGui.QApplication.translate("Settings", "Header 2 Font", None, QtGui.QApplication.UnicodeUTF8))
        self.header3FontButton.setText(QtGui.QApplication.translate("Settings", "Header 3 Font", None, QtGui.QApplication.UnicodeUTF8))
        self.header4FontButton.setText(QtGui.QApplication.translate("Settings", "Header 4 Font", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colorsTab), QtGui.QApplication.translate("Settings", "Highlighting, Colors, and Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setToolTip(QtGui.QApplication.translate("Settings", "Restores settings to what they were when you opened the window", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setText(QtGui.QApplication.translate("Settings", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setToolTip(QtGui.QApplication.translate("Settings", "Apply new speech settings", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Settings", "Apply", None, QtGui.QApplication.UnicodeUTF8))

