# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W:\Documents\Special Projects\Graffe, Spencer\workspace2\another\src\forms/settings.ui'
#
# Created: Mon Apr 15 08:41:12 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(589, 471)
        font = QtGui.QFont()
        font.setPointSize(12)
        Settings.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.speechTab = QtGui.QWidget()
        self.speechTab.setObjectName(_fromUtf8("speechTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.speechTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.speechTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.speechTab)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.speechTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.rateSlider = QtGui.QSlider(self.speechTab)
        self.rateSlider.setMinimumSize(QtCore.QSize(201, 0))
        self.rateSlider.setMinimum(100)
        self.rateSlider.setMaximum(300)
        self.rateSlider.setProperty("value", 200)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setObjectName(_fromUtf8("rateSlider"))
        self.gridLayout.addWidget(self.rateSlider, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.speechTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.volumeSlider = QtGui.QSlider(self.speechTab)
        self.volumeSlider.setMinimumSize(QtCore.QSize(201, 0))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 99)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.gridLayout.addWidget(self.volumeSlider, 1, 2, 1, 1)
        self.rateLabel = QtGui.QLabel(self.speechTab)
        self.rateLabel.setObjectName(_fromUtf8("rateLabel"))
        self.gridLayout.addWidget(self.rateLabel, 0, 1, 1, 1)
        self.volumeLabel = QtGui.QLabel(self.speechTab)
        self.volumeLabel.setObjectName(_fromUtf8("volumeLabel"))
        self.gridLayout.addWidget(self.volumeLabel, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.testSpeechText = QtGui.QPlainTextEdit(self.speechTab)
        self.testSpeechText.setObjectName(_fromUtf8("testSpeechText"))
        self.horizontalLayout_2.addWidget(self.testSpeechText)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.testButton = QtGui.QPushButton(self.speechTab)
        self.testButton.setIconSize(QtCore.QSize(50, 50))
        self.testButton.setObjectName(_fromUtf8("testButton"))
        self.verticalLayout_2.addWidget(self.testButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.speechTab, _fromUtf8(""))
        self.colorsTab = QtGui.QWidget()
        self.colorsTab.setObjectName(_fromUtf8("colorsTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.colorsTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.colorsTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.contentBackgroundButton = QtGui.QPushButton(self.colorsTab)
        self.contentBackgroundButton.setObjectName(_fromUtf8("contentBackgroundButton"))
        self.horizontalLayout_3.addWidget(self.contentBackgroundButton)
        self.contentTextButton = QtGui.QPushButton(self.colorsTab)
        self.contentTextButton.setObjectName(_fromUtf8("contentTextButton"))
        self.horizontalLayout_3.addWidget(self.contentTextButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.highlighterBackgroundButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterBackgroundButton.setObjectName(_fromUtf8("highlighterBackgroundButton"))
        self.horizontalLayout_4.addWidget(self.highlighterBackgroundButton)
        self.highlighterTextButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterTextButton.setObjectName(_fromUtf8("highlighterTextButton"))
        self.horizontalLayout_4.addWidget(self.highlighterTextButton)
        self.line = QtGui.QFrame(self.colorsTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.enableHighlightCheckbox = QtGui.QCheckBox(self.colorsTab)
        self.enableHighlightCheckbox.setObjectName(_fromUtf8("enableHighlightCheckbox"))
        self.horizontalLayout_4.addWidget(self.enableHighlightCheckbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(self.colorsTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.highlighterLineBackgroundButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterLineBackgroundButton.setObjectName(_fromUtf8("highlighterLineBackgroundButton"))
        self.horizontalLayout_5.addWidget(self.highlighterLineBackgroundButton)
        self.highlighterLineTextButton = QtGui.QPushButton(self.colorsTab)
        self.highlighterLineTextButton.setObjectName(_fromUtf8("highlighterLineTextButton"))
        self.horizontalLayout_5.addWidget(self.highlighterLineTextButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_5 = QtGui.QLabel(self.colorsTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.tabWidget.addTab(self.colorsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.restoreButton = QtGui.QPushButton(Settings)
        self.restoreButton.setObjectName(_fromUtf8("restoreButton"))
        self.horizontalLayout.addWidget(self.restoreButton)
        self.applyButton = QtGui.QPushButton(Settings)
        self.applyButton.setIconSize(QtCore.QSize(50, 50))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.horizontalLayout.addWidget(self.applyButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Settings", None))
        self.label.setText(_translate("Settings", "Words Per Minute:", None))
        self.comboBox.setToolTip(_translate("Settings", "Drop down box for selecting the voice", None))
        self.label_2.setText(_translate("Settings", "Volume:", None))
        self.rateSlider.setToolTip(_translate("Settings", "Words per minute slider (rate)", None))
        self.label_3.setText(_translate("Settings", "Voices:", None))
        self.volumeSlider.setToolTip(_translate("Settings", "Volume slider", None))
        self.rateLabel.setText(_translate("Settings", "100", None))
        self.volumeLabel.setText(_translate("Settings", "200", None))
        self.testSpeechText.setToolTip(_translate("Settings", "The text entered here is used when the test speech button is pressed", None))
        self.testSpeechText.setPlainText(_translate("Settings", "This is a test of the current text to speech settings.", None))
        self.testButton.setToolTip(_translate("Settings", "Apply and test current speech settings", None))
        self.testButton.setText(_translate("Settings", "Test Speech", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.speechTab), _translate("Settings", "Speech", None))
        self.label_6.setText(_translate("Settings", "Content:", None))
        self.contentBackgroundButton.setText(_translate("Settings", "Background", None))
        self.contentTextButton.setText(_translate("Settings", "Text", None))
        self.highlighterBackgroundButton.setText(_translate("Settings", "Background", None))
        self.highlighterTextButton.setText(_translate("Settings", "Text", None))
        self.enableHighlightCheckbox.setText(_translate("Settings", "Enable", None))
        self.label_4.setText(_translate("Settings", "Highlighter Text:", None))
        self.highlighterLineBackgroundButton.setText(_translate("Settings", "Background", None))
        self.highlighterLineTextButton.setText(_translate("Settings", "Text", None))
        self.label_5.setText(_translate("Settings", "Highlighter Line:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colorsTab), _translate("Settings", "Highlighting and Colors", None))
        self.restoreButton.setToolTip(_translate("Settings", "Restores settings to what they were when you opened the window", None))
        self.restoreButton.setText(_translate("Settings", "Restore", None))
        self.applyButton.setToolTip(_translate("Settings", "Apply new speech settings", None))
        self.applyButton.setText(_translate("Settings", "Apply", None))

