# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/atrctech/Desktop/workspace/NiftyProseArticulator/src/forms/speech_settings.ui'
#
# Created: Fri Sep 13 14:31:12 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SpeechSettings(object):
    def setupUi(self, SpeechSettings):
        SpeechSettings.setObjectName("SpeechSettings")
        SpeechSettings.resize(408, 539)
        font = QtGui.QFont()
        font.setPointSize(12)
        SpeechSettings.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/system_config_services.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpeechSettings.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(SpeechSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(SpeechSettings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.rateSlider = QtGui.QSlider(SpeechSettings)
        self.rateSlider.setMinimumSize(QtCore.QSize(201, 0))
        self.rateSlider.setMinimum(0)
        self.rateSlider.setMaximum(100)
        self.rateSlider.setProperty("value", 50)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.rateSlider.setTickInterval(10)
        self.rateSlider.setObjectName("rateSlider")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.rateSlider)
        self.label_2 = QtGui.QLabel(SpeechSettings)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.volumeSlider = QtGui.QSlider(SpeechSettings)
        self.volumeSlider.setMinimumSize(QtCore.QSize(201, 0))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.volumeSlider.setTickInterval(10)
        self.volumeSlider.setObjectName("volumeSlider")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.volumeSlider)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout.setItem(4, QtGui.QFormLayout.FieldRole, spacerItem)
        self.label_3 = QtGui.QLabel(SpeechSettings)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.voiceComboBox = QtGui.QComboBox(SpeechSettings)
        self.voiceComboBox.setEditable(False)
        self.voiceComboBox.setObjectName("voiceComboBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.voiceComboBox)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout.setItem(6, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.label_5 = QtGui.QLabel(SpeechSettings)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_5)
        self.mathDatabaseComboBox = QtGui.QComboBox(SpeechSettings)
        self.mathDatabaseComboBox.setObjectName("mathDatabaseComboBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.mathDatabaseComboBox)
        self.label_4 = QtGui.QLabel(SpeechSettings)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageTagCheckBox = QtGui.QCheckBox(SpeechSettings)
        self.imageTagCheckBox.setObjectName("imageTagCheckBox")
        self.horizontalLayout_3.addWidget(self.imageTagCheckBox)
        self.mathTagCheckBox = QtGui.QCheckBox(SpeechSettings)
        self.mathTagCheckBox.setObjectName("mathTagCheckBox")
        self.horizontalLayout_3.addWidget(self.mathTagCheckBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.pauseSlider = QtGui.QSlider(SpeechSettings)
        self.pauseSlider.setMaximum(10)
        self.pauseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pauseSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.pauseSlider.setTickInterval(1)
        self.pauseSlider.setObjectName("pauseSlider")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pauseSlider)
        self.label_6 = QtGui.QLabel(SpeechSettings)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.testSpeechText = QtGui.QPlainTextEdit(SpeechSettings)
        self.testSpeechText.setObjectName("testSpeechText")
        self.horizontalLayout_2.addWidget(self.testSpeechText)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.testButton = QtGui.QPushButton(SpeechSettings)
        self.testButton.setIconSize(QtCore.QSize(50, 50))
        self.testButton.setObjectName("testButton")
        self.verticalLayout_2.addWidget(self.testButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.restoreButton = QtGui.QPushButton(SpeechSettings)
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout.addWidget(self.restoreButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.applyButton = QtGui.QPushButton(SpeechSettings)
        self.applyButton.setIconSize(QtCore.QSize(50, 50))
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(SpeechSettings)
        QtCore.QMetaObject.connectSlotsByName(SpeechSettings)
        SpeechSettings.setTabOrder(self.rateSlider, self.volumeSlider)
        SpeechSettings.setTabOrder(self.volumeSlider, self.voiceComboBox)
        SpeechSettings.setTabOrder(self.voiceComboBox, self.imageTagCheckBox)
        SpeechSettings.setTabOrder(self.imageTagCheckBox, self.mathTagCheckBox)
        SpeechSettings.setTabOrder(self.mathTagCheckBox, self.testSpeechText)
        SpeechSettings.setTabOrder(self.testSpeechText, self.testButton)
        SpeechSettings.setTabOrder(self.testButton, self.restoreButton)
        SpeechSettings.setTabOrder(self.restoreButton, self.applyButton)

    def retranslateUi(self, SpeechSettings):
        SpeechSettings.setWindowTitle(QtGui.QApplication.translate("SpeechSettings", "Speech", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SpeechSettings", "Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.rateSlider.setToolTip(QtGui.QApplication.translate("SpeechSettings", "Words per minute slider (rate)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SpeechSettings", "Volume:", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeSlider.setToolTip(QtGui.QApplication.translate("SpeechSettings", "Volume slider", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SpeechSettings", "Voices:", None, QtGui.QApplication.UnicodeUTF8))
        self.voiceComboBox.setToolTip(QtGui.QApplication.translate("SpeechSettings", "Drop down box for selecting the voice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SpeechSettings", "Math:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SpeechSettings", "Announce:", None, QtGui.QApplication.UnicodeUTF8))
        self.imageTagCheckBox.setText(QtGui.QApplication.translate("SpeechSettings", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.mathTagCheckBox.setText(QtGui.QApplication.translate("SpeechSettings", "Math", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SpeechSettings", "Pause Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.testSpeechText.setToolTip(QtGui.QApplication.translate("SpeechSettings", "The text entered here is used when the test speech button is pressed", None, QtGui.QApplication.UnicodeUTF8))
        self.testSpeechText.setPlainText(QtGui.QApplication.translate("SpeechSettings", "This is a test of the current text to speech settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setToolTip(QtGui.QApplication.translate("SpeechSettings", "Apply and test current speech settings", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("SpeechSettings", "Test Speech", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setToolTip(QtGui.QApplication.translate("SpeechSettings", "Restores settings to what they were when you opened the window", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setText(QtGui.QApplication.translate("SpeechSettings", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setToolTip(QtGui.QApplication.translate("SpeechSettings", "Apply new speech settings", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("SpeechSettings", "Apply", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
