[package]
name = "central-access-reader"
version = "0.0.1"
authors = ["Spencer Graffe <sgraffe@gmail.com>"]

[lib]
name = "central_access_reader"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
objc = "0.2.2"