# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W:\Nifty Prose Articulator\workspace2\another\src\mathml\pattern_editor\forms/patterneditorwindow.ui'
#
# Created: Fri Jun 07 15:46:35 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PatternEditorWindow(object):
    def setupUi(self, PatternEditorWindow):
        PatternEditorWindow.setObjectName(_fromUtf8("PatternEditorWindow"))
        PatternEditorWindow.resize(1096, 631)
        font = QtGui.QFont()
        font.setPointSize(12)
        PatternEditorWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(PatternEditorWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.speakButton = QtGui.QPushButton(self.centralwidget)
        self.speakButton.setObjectName(_fromUtf8("speakButton"))
        self.horizontalLayout.addWidget(self.speakButton)
        self.outputText = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputText.sizePolicy().hasHeightForWidth())
        self.outputText.setSizePolicy(sizePolicy)
        self.outputText.setMaximumSize(QtCore.QSize(16777215, 50))
        self.outputText.setObjectName(_fromUtf8("outputText"))
        self.horizontalLayout.addWidget(self.outputText)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(10)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.databaseLabel = QtGui.QLabel(self.widget)
        self.databaseLabel.setObjectName(_fromUtf8("databaseLabel"))
        self.verticalLayout_4.addWidget(self.databaseLabel)
        self.databaseEditor = Qsci.QsciScintilla(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.databaseEditor.setFont(font)
        self.databaseEditor.setToolTip(_fromUtf8(""))
        self.databaseEditor.setWhatsThis(_fromUtf8(""))
        self.databaseEditor.setObjectName(_fromUtf8("databaseEditor"))
        self.verticalLayout_4.addWidget(self.databaseEditor)
        self.widget1 = QtGui.QWidget(self.splitter_2)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.mathmlEditor = Qsci.QsciScintilla(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.mathmlEditor.setFont(font)
        self.mathmlEditor.setToolTip(_fromUtf8(""))
        self.mathmlEditor.setWhatsThis(_fromUtf8(""))
        self.mathmlEditor.setObjectName(_fromUtf8("mathmlEditor"))
        self.verticalLayout_3.addWidget(self.mathmlEditor)
        self.splitter = QtGui.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.widget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.mathmlCodesList = QtGui.QListWidget(self.widget2)
        self.mathmlCodesList.setObjectName(_fromUtf8("mathmlCodesList"))
        self.verticalLayout_2.addWidget(self.mathmlCodesList)
        self.widget3 = QtGui.QWidget(self.splitter)
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.expandAllButton = QtGui.QPushButton(self.widget3)
        self.expandAllButton.setObjectName(_fromUtf8("expandAllButton"))
        self.horizontalLayout_2.addWidget(self.expandAllButton)
        self.collapseAllButton = QtGui.QPushButton(self.widget3)
        self.collapseAllButton.setObjectName(_fromUtf8("collapseAllButton"))
        self.horizontalLayout_2.addWidget(self.collapseAllButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stagesTreeView = QtGui.QTreeView(self.widget3)
        self.stagesTreeView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.stagesTreeView.setRootIsDecorated(True)
        self.stagesTreeView.setHeaderHidden(True)
        self.stagesTreeView.setObjectName(_fromUtf8("stagesTreeView"))
        self.stagesTreeView.header().setVisible(False)
        self.verticalLayout.addWidget(self.stagesTreeView)
        self.verticalLayout_5.addWidget(self.splitter_3)
        self.verticalLayout_5.setStretch(1, 1)
        PatternEditorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PatternEditorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        PatternEditorWindow.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(PatternEditorWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(PatternEditorWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(PatternEditorWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(PatternEditorWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionQuit = QtGui.QAction(PatternEditorWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen_MathML = QtGui.QAction(PatternEditorWindow)
        self.actionOpen_MathML.setObjectName(_fromUtf8("actionOpen_MathML"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_MathML)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PatternEditorWindow)
        QtCore.QMetaObject.connectSlotsByName(PatternEditorWindow)

    def retranslateUi(self, PatternEditorWindow):
        PatternEditorWindow.setWindowTitle(_translate("PatternEditorWindow", "MathML Pattern Editor", None))
        self.speakButton.setToolTip(_translate("PatternEditorWindow", "Parses and speaks the MathML (Ctrl+R works too)", None))
        self.speakButton.setText(_translate("PatternEditorWindow", "Speak", None))
        self.speakButton.setShortcut(_translate("PatternEditorWindow", "Ctrl+R", None))
        self.databaseLabel.setText(_translate("PatternEditorWindow", "Database", None))
        self.label_4.setText(_translate("PatternEditorWindow", "MathML", None))
        self.label_5.setText(_translate("PatternEditorWindow", "Equations", None))
        self.label_2.setText(_translate("PatternEditorWindow", "Stages", None))
        self.expandAllButton.setText(_translate("PatternEditorWindow", "Expand All", None))
        self.collapseAllButton.setText(_translate("PatternEditorWindow", "Collapse All", None))
        self.menuFile.setTitle(_translate("PatternEditorWindow", "File", None))
        self.actionNew.setText(_translate("PatternEditorWindow", "New", None))
        self.actionNew.setShortcut(_translate("PatternEditorWindow", "Ctrl+N", None))
        self.actionOpen.setText(_translate("PatternEditorWindow", "Open Database", None))
        self.actionOpen.setShortcut(_translate("PatternEditorWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("PatternEditorWindow", "Save", None))
        self.actionSave.setShortcut(_translate("PatternEditorWindow", "Ctrl+S", None))
        self.actionSave_As.setText(_translate("PatternEditorWindow", "Save As", None))
        self.actionSave_As.setShortcut(_translate("PatternEditorWindow", "Ctrl+Shift+S", None))
        self.actionQuit.setText(_translate("PatternEditorWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("PatternEditorWindow", "Ctrl+Q", None))
        self.actionOpen_MathML.setText(_translate("PatternEditorWindow", "Open MathML", None))
        self.actionOpen_MathML.setShortcut(_translate("PatternEditorWindow", "Ctrl+Shift+O", None))

from PyQt4 import Qsci
